Basic .nvmrc file support.
coreybutler/nvm-windows pull request #594
Opened 2020-12-13 06:16 UTC by wsobolewski

2021-01-14 07:30 UTC, duszekmestre requested changes

2021-01-14 07:30 UTC, duszekmestre commented on src/nvm.go
> +		} else {
Pls align indentation with other code

2021-01-14 07:30 UTC, duszekmestre commented on src/nvm.go
> +		}
Pls align indentation with other code

2021-01-14 07:30 UTC, duszekmestre commented on src/nvm.go
> +  if err == nil {
What if error occured? Maybe you should print error message in that case?

2021-01-28 13:19 UTC, aakash-verma-aurea commented
@duszekmestre any more help needed? Or are we good to merge this?

2021-08-31 00:19 UTC, celioreyes commented
Was thinking of implementing this since I noticed `.nvmrc` support wasn't already implemented.

Anything in particular blocking this PR from being merged?

2022-02-04 21:00 UTC, it-rec commented
We have 2022 and this is still not merged nor any other comment after the fixes was made. It would be superb to get this soon!

2022-02-04 21:53 UTC, coreybutler commented
While I appreciate the contribution, I do not plan to merge this. Please see the [reasons why](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#why-isnt-nvmrc-supported-why-arent-some-nvm-for-macoslinux-features-supported).

2022-02-04 21:53 UTC, closed without merging