Allow `nvm use` to be called with the part of the semver
coreybutler/nvm-windows pull request #709
Opened 2021-12-16 13:55 UTC by vladonemo

For instance, the `nvm use 12` will switch to the latest installed version of 12.*. Similarly, `nvm use 12.22` will switch to the latest installed version of 12.22.*

Fixes #708

2021-12-27 09:30 UTC, vladonemo commented
@coreybutler any chance of reviewing this one? Thanks

2021-12-27 14:20 UTC, coreybutler commented
Not during the holiday break.

2022-01-16 15:50 UTC, acnn commented on src/nvm.go
> -	if err != nil {
@vladonemo Is this condition still required at the below line?
https://github.com/coreybutler/nvm-windows/blob/master/src/nvm.go#L272
Looks like `getVersion` already handles the partial version input correctly?

2022-01-17 06:27 UTC, vladonemo commented on src/nvm.go
> -	if err != nil {
right, it is not required. Nice catch.
As this is not part of my changes, I wouldn't remove it in this PR, but rather create a new PR.

2022-02-03 14:05 UTC, vladonemo commented
@coreybutler any chance you get around to it? This utility is great, would be awesome to improve the usability here

2022-03-08 14:32 UTC, coreybutler requested changes
This looks good, except for the removed error handling. See comments for details.

2022-03-08 14:32 UTC, coreybutler commented on src/nvm.go
> -	if err != nil {
Is there a reason the error handling is removed? It is still possible to produce this error even if the `v` is stripped from the version. 

Ultimately, the version check needs to be more specific -  such as only removing preceding characters, not necessarily builds (such as 1.2.3-beta.v1). However; that is something I can add later.

I'd feel comfortable merging this PR if this error handling is not removed.

2022-03-13 02:33 UTC, ajmeese7 commented
@vladonemo have you had a chance to check out the comments above? I would love to see it merged!

2022-04-20 17:02 UTC, vladonemo commented
@coreybutler I have reverted the error handling changes long time back. Any chance merging this one?

2022-04-21 18:21 UTC, kellypleahy commented on src/nvm.go
> +					current, _ := semver.New(versionNumberFrom(v))
Shouldn't this be referring to the 'result' variable, instead of v like the result variable above?

2022-04-21 19:34 UTC, vladonemo commented on src/nvm.go
> +					current, _ := semver.New(versionNumberFrom(v))
oh, thanks a lot. Yep, right. Though it doesn't really matter in the context this piece of code is called - the list of versions is sorted descending, hence the first version in the list is always the latest one.

2022-04-21 19:36 UTC, vladonemo commented
@coreybutler I had to change the error handling mentioned above once more. After I added it back (on your request), the most important use cases of this feature PR stopped working (e.g. `nvm use 16` reported `node v16.14.2 (64-bit) is not installed or cannot be found.` even though it was installed)

2022-04-25 04:59 UTC, r3faat1 commented
Can we get this or similar implemented soon? The command `nvm use 16` is throwing error: `node vv16.14.0 (64-bit) is not installed or cannot be found.`

2022-05-01 19:08 UTC, coreybutler commented on src/nvm.go
> +	version, cpuarch, err := getVersion(version, cpuarch, true)
@vladonemo is this the line that's preventing the main use case from succeeding?

2022-05-02 06:47 UTC, vladonemo commented on src/nvm.go
> +	version, cpuarch, err := getVersion(version, cpuarch, true)
the call returns an installed version, but it also returns the error in case user only provided part of the SemVer.

2022-05-11 19:37 UTC, vladonemo commented
@coreybutler this PR has been open since half a year now. Is there any chance that it gets closed? I'd like to avoid distributing a patched version to our teams and use the official release instead.

2022-05-11 20:09 UTC, coreybutler commented on src/nvm.go
> +	version, cpuarch, err := getVersion(version, cpuarch, true)
The code should check to see if the error message indicates it is a partial version. If it _is_ a partial, the error can be ignored. If it is **not** a partial, the error should be thrown.

2022-05-12 11:12 UTC, vladonemo commented on src/nvm.go
> +	version, cpuarch, err := getVersion(version, cpuarch, true)
right. And this is what the code does at the moment - line 524. If the error is **not** a partial, it fails with this error. Otherwise it continues, because the `getVersion` could resolve the latest sub version.

2022-05-12 12:23 UTC, coreybutler commented on src/nvm.go
> +	version, cpuarch, err := getVersion(version, cpuarch, true)
apologies - I was just looking at the changes, not the full file. I see this is the logic that exists.

2022-05-12 12:26 UTC, coreybutler approved these changes

2022-05-12 12:26 UTC, merged

2022-05-12 12:27 UTC, coreybutler commented
Merged. This will be in the next release, but there are several other PRs to review before I can cut a new release.